language: android
jdk: oraclejdk8
sudo: true
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
#  - extra-android-m2repository
#  - extra-android-support
script:
- "./gradlew assembleRelease"
before_install:
- chmod +x gradlew
- gem install fir-cli #安装fir命令行客户端
deploy:
  provider: releases
  api_key:
    secure: WCwcM3iKWQKKV4DcMAdAlPUyk/jYnRfmrb656knoGdiK8DGZ7JDNgkL+xxcGmkbHOOdIGexk71x1/xt/qQcm2Kv+q7PUc3FfLn7bLOlWh41jBDLCUQ9Zj9GleujpFHgJ4iXonKP4xtJMsNHe+ff4GPNJYM5xETUR40ApAp0Y2Dau4J+QsO2p8Z+Cwcj+xaaczWNHQ1/+Y4csd6/qSmd3EFklPhUy4AMtxzuW2umzfhJtIKGg3iaDQD7GUz3/8Kz6wfHsUNx2T1z0sFZ/KJPS4Q3cYrFTn1e9aZBDKYv5eIlCW6AZU9lsjU+qSioOAVx9SNL4/teGFQRyg60OC3UyXrK0AN4J1JCUY0EqxJNOqDJAVWQvPUXEhAvY/3Au2Hyrj0M+LRWMwncJXoDtqOPtRjymi/i/G6iXwv20qZj0VElMd1QfLViHMyOkamK9k1AaerOUeUjK3Ln5G7f+jkDk9jxHRbhFDFycbn27SHKdgaUhsRlVOeBJ4Duw4e1tl8sqrqEXtpTtR2Ieh6bO2WhqshqRiCMqh6dr7vkw3b28hafpy3mJWSU6ILshZOWwOJ1xqabVSdNY5BY7TkM+5R9V7Ww2WWoA8Co9HsiC01AfPyEWRYYoRhH8BI/fXJBIXz7aHYl3BUnamb0WPOwFlHsRykYCpgYHd2jgNn2EwjT25p8=
  file: LibPatronus/build/outputs/aar/LibPatronus-release.aar
  skip_cleanup: true
  on:
    repo: wildcreek/Patronus
after_deploy:
  - fir login 13181251771eb3db1e538c47ea8d993b #fir账号的Token
  - fir me #打印身份信息,验证是否登录成功
  - fir p LibPatronus/build/outputs/aar/LibPatronus-release.aar #自动发布应用至fir内测平台